server:
 port: 8081
spring:
 cloud:
  config:
   server:
    git:
     default-label: master
     uri: https://github.com/EdisonValle26/Service-configuration
     search-paths: config-data
 application:
  name: config-server
