INSERT INTO COFFEE(ID, NAME) VALUES ('10001', 'Café Cereza');
INSERT INTO COFFEE(ID, NAME) VALUES ('10002', 'Café Ganador');
INSERT INTO COFFEE(ID, NAME) VALUES ('10003', 'Café Lareño');
INSERT INTO COFFEE(ID, NAME) VALUES ('10004', 'Café Três Pontas');
INSERT INTO COFFEE(ID, NAME) VALUES ('10005', 'Café Três Pontas');
INSERT INTO COFFEE(ID, NAME) VALUES ('10006', 'Café Três Pontas');
INSERT INTO COFFEE(ID, NAME) VALUES ('10007', 'Café Três Pontas');